config-version: 2

name: 'databricks_tpch'
version: '1.0.0'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  databricks_tpch:
    marts:
      materialized: table
    